/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/
// allow-any-unicode-comment-file (Para Code: this file contains Japanese PARA-PATCH/PARA-CODE comments)

// PARA-CODE: fork-owned file (Para Code) — not present in upstream microsoft/vscode. See CLAUDE.md.

// エージェントCLI (Claude Code / Codex) の通知hookを自動設置する (Superset の setupAgentHooks 移植)。
// shared process の ParadisAgentBrowserService 起動時に冪等実行される。
// 1. ~/.para-code/hooks/notify-vN.sh を生成 (実行権付き)。スクリプトは Para Code のターミナル外
//    (ペイントークンenvなし) ではstdinを読み切って破棄してから exit 0 する無害設計。
// 2. ~/.claude/settings.json へhook定義を冪等マージ (既存のユーザーhookは保持)。
// 3. ~/.codex/hooks.json へhook定義を冪等マージ (同上)。
// 既存ファイルのJSONパースに失敗した場合は何も書かない (ユーザーファイルを壊すくらいなら諦める)。

import { execFile } from 'child_process';
import { promises as fs, readFileSync, watch, writeFileSync } from 'fs';
import { homedir } from 'os';
import { basename, dirname, join } from '../../../../base/common/path.js';
import { Disposable, IDisposable, toDisposable } from '../../../../base/common/lifecycle.js';
import { findExecutable } from '../../../../base/node/processes.js';
import { ILogService } from '../../../../platform/log/common/log.js';
import { PARADIS_MCP_PORT_FILE_ENV_VAR, PARADIS_PANE_TOKEN_ENV_VAR } from '../common/paradisAgentBrowser.js';
import { IParadisManagedHookEvent, PARADIS_AGENT_HOOK_MAX_BODY_BYTES, PARADIS_AGENT_HOOK_SCHEMA_VERSION, PARADIS_CLAUDE_ACTIVITY_HOOK_EVENTS, PARADIS_CLAUDE_HOOK_EVENTS, PARADIS_CLAUDE_MESSAGE_DISPLAY_HOOK_EVENT, PARADIS_CODEX_HOOK_EVENTS, PARADIS_LEGACY_NOTIFY_HOOK_RELATIVE_PATHS, PARADIS_NOTIFY_HOOK_RELATIVE_PATH, PARADIS_NOTIFY_HOOK_RELATIVE_PATH_PS1, paradisManagedAgentHookCommandWindows, paradisManagedHookDefinition } from '../common/paradisAgentHooks.js';
import { paradisClaudeConfigDir, paradisCodexHome } from './paradisAgentHome.js';

/**
 * notify.sh の内容を生成する (全行ASCII)。jq には依存せず grep/sed のみでパースする。
 * - Para Code のターミナル外 (env なし) でもstdinを読み切ってからexit 0
 * - イベント名は stdin JSON の `hook_event_name` (Claude Code) / `type` (Codex notify) から取得。
 *   パース失敗時は黙って捨てる (誤った完了通知より安全)
 * - curl の失敗が hook 全体を fail させないよう `|| true` で必ず正常終了する
 */
export function paradisGetNotifyScriptContent(): string {
	return [
		'#!/bin/sh',
		'# Para Code agent notification hook schema v2',
		'# Auto-generated by Para Code (paradisAgentHooksSetup.ts); regenerated on startup.',
		'# Forwards Claude Code / Codex hook events to the Para Code shared process',
		'# (POST /agent-hook). Outside Para Code terminals stdin is drained and discarded.',
		'',
		'# A global hook may run outside Para Code. Keep the writer alive until EOF.',
		'drain_stdin() {',
		'  if [ -z "${1:-}" ]; then',
		'    cat >/dev/null 2>&1 || true',
		'  fi',
		'}',
		'',
		`if [ -z "\${${PARADIS_PANE_TOKEN_ENV_VAR}:-}" ] || [ -z "\${${PARADIS_MCP_PORT_FILE_ENV_VAR}:-}" ] || [ ! -f "$${PARADIS_MCP_PORT_FILE_ENV_VAR}" ]; then`,
		'  drain_stdin "${1:-}"',
		'  exit 0',
		'fi',
		'',
		`PORT=$(sed -nE 's/.*"port"[[:space:]]*:[[:space:]]*([0-9]+).*/\\1/p' "$${PARADIS_MCP_PORT_FILE_ENV_VAR}" 2>/dev/null | head -n 1)`,
		'if [ -z "$PORT" ]; then',
		'  drain_stdin "${1:-}"',
		'  exit 0',
		'fi',
		'',
		'# Spool active payloads without retaining multi-megabyte JSON in a shell variable.',
		'umask 077',
		'INPUT_FILE=$(mktemp "${TMPDIR:-/tmp}/para-code-hook.XXXXXX" 2>/dev/null) || {',
		'  drain_stdin "${1:-}"',
		'  exit 0',
		'}',
		'trap \'rm -f "$INPUT_FILE"\' 0',
		'trap \'exit 0\' 1 2 15',
		'# Codex legacy notify passes JSON as argv[1]; hooks pipe JSON via stdin.',
		'if [ -n "${1:-}" ]; then',
		'  printf \'%s\' "$1" >"$INPUT_FILE" 2>/dev/null || exit 0',
		'else',
		`  if ! head -c ${PARADIS_AGENT_HOOK_MAX_BODY_BYTES + 1} >"$INPUT_FILE" 2>/dev/null; then`,
		'    cat >/dev/null 2>&1 || true',
		'    exit 0',
		'  fi',
		'  cat >/dev/null 2>&1 || true',
		'fi',
		'',
		'# Claude Code uses "hook_event_name"; Codex uses "type". No jq dependency.',
		`EVENT=$(grep -oE '"hook_event_name"[[:space:]]*:[[:space:]]*"[^"]*"' "$INPUT_FILE" 2>/dev/null | head -n 1 | sed -E 's/.*"([^"]*)"$/\\1/')`,
		'if [ -z "$EVENT" ]; then',
		`  EVENT=$(grep -oE '"type"[[:space:]]*:[[:space:]]*"[^"]*"' "$INPUT_FILE" 2>/dev/null | head -n 1 | sed -E 's/.*"([^"]*)"$/\\1/')`,
		'fi',
		'# Never guess on parse failure: dropping is safer than a false notification.',
		'[ -n "$EVENT" ] || exit 0',
		'# Keep the query value URL-safe (event names are plain identifiers).',
		`EVENT=$(printf '%s' "$EVENT" | tr -cd 'A-Za-z0-9._-')`,
		'[ -n "$EVENT" ] || exit 0',
		'# Fire-and-forget; a failed curl must never fail the agent hook.',
		'# POST the raw hook JSON so the shared process can read session_id /',
		'# transcript_path (used by the mobile agent-chat mirror). The event query',
		'# parameter is kept for the status logic and for backward compatibility.',
		`HOOK_URL="http://127.0.0.1:$PORT/agent-hook?pane=$${PARADIS_PANE_TOKEN_ENV_VAR}&event=$EVENT"`,
		'INPUT_BYTES=$(wc -c <"$INPUT_FILE" 2>/dev/null | tr -d \'[:space:]\')',
		'case "$INPUT_BYTES" in',
		'  ""|*[!0-9]*) exit 0 ;;',
		'esac',
		`if [ "$INPUT_BYTES" -gt ${PARADIS_AGENT_HOOK_MAX_BODY_BYTES} ]; then`,
		'  curl -s -m 3 "$HOOK_URL" >/dev/null 2>&1 || true',
		'else',
		'  curl -s -m 3 -X POST -H "Content-Type: application/json" --data-binary @"$INPUT_FILE" "$HOOK_URL" >/dev/null 2>&1 || true',
		'fi',
		'exit 0',
		'',
	].join('\n');
}

/**
 * notify.ps1 の内容を生成する (全行ASCII、Windows用)。役割・防御方針は notify.sh と同一:
 * - Para Code のターミナル外 (env なし) でもstdinを読み切ってからexit 0
 * - イベント名は stdin JSON (Claude Code / Codex 新hooks) の `hook_event_name`、
 *   または argv[1] (Codex legacy notify) の `type` から取得。パース失敗は黙って捨てる
 * - POST の失敗が hook 全体を fail させないよう try/catch で必ず正常終了する
 */
export function paradisGetNotifyScriptContentPs1(): string {
	return [
		'# Para Code agent notification hook schema v2 (PowerShell)',
		'# Auto-generated by Para Code (paradisAgentHooksSetup.ts); regenerated on startup.',
		'# Forwards Claude Code / Codex hook events to the Para Code shared process',
		'# (POST /agent-hook). Outside Para Code terminals stdin is drained and discarded.',
		'param([string]$HookArg)',
		'$ErrorActionPreference = \'SilentlyContinue\'',
		'function Drain-StandardInput {',
		'  if ($HookArg) { return }',
		'  try {',
		'    $stream = [Console]::OpenStandardInput()',
		'    $buffer = New-Object byte[] 8192',
		'    while ($stream.Read($buffer, 0, $buffer.Length) -gt 0) { }',
		'  } catch { }',
		'}',
		'function Read-BoundedStandardInput {',
		`  $captureLimit = ${PARADIS_AGENT_HOOK_MAX_BODY_BYTES + 1}`,
		'  $stream = [Console]::OpenStandardInput()',
		'  $buffer = New-Object byte[] 8192',
		'  $captured = New-Object System.IO.MemoryStream',
		'  try {',
		'    while (($read = $stream.Read($buffer, 0, $buffer.Length)) -gt 0) {',
		'      $remaining = $captureLimit - [int]$captured.Length',
		'      if ($remaining -gt 0) {',
		'        $captured.Write($buffer, 0, [Math]::Min($read, $remaining))',
		'      }',
		'    }',
		'    $result = $captured.ToArray()',
		'    return ,$result',
		'  } finally {',
		'    $captured.Dispose()',
		'  }',
		'}',
		`if (-not $env:${PARADIS_PANE_TOKEN_ENV_VAR} -or -not $env:${PARADIS_MCP_PORT_FILE_ENV_VAR} -or -not (Test-Path -LiteralPath $env:${PARADIS_MCP_PORT_FILE_ENV_VAR})) {`,
		'  Drain-StandardInput',
		'  exit 0',
		'}',
		'',
		'# Codex legacy notify passes JSON as argv[1]; hooks pipe JSON via stdin.',
		'[byte[]]$bodyBytes = @()',
		'try {',
		'  if ($HookArg) {',
		'    $bodyBytes = [System.Text.Encoding]::UTF8.GetBytes($HookArg)',
		'  } else {',
		'    $bodyBytes = Read-BoundedStandardInput',
		'  }',
		'} catch { exit 0 }',
		'$inputJson = [System.Text.Encoding]::UTF8.GetString($bodyBytes)',
		'if (-not $inputJson) { exit 0 }',
		'',
		'# Claude Code and Codex hooks use "hook_event_name"; Codex legacy notify uses "type".',
		'$eventMatch = [regex]::Match($inputJson, \'"hook_event_name"\\s*:\\s*"([^"]*)"\')',
		'if (-not $eventMatch.Success) { $eventMatch = [regex]::Match($inputJson, \'"type"\\s*:\\s*"([^"]*)"\') }',
		'# Never guess on parse failure: dropping is safer than a false notification.',
		'if (-not $eventMatch.Success) { exit 0 }',
		'# Keep the query value URL-safe (event names are plain identifiers).',
		'$eventName = $eventMatch.Groups[1].Value -replace \'[^A-Za-z0-9._-]\', \'\'',
		'if (-not $eventName) { exit 0 }',
		'',
		`$portMatch = [regex]::Match((Get-Content -LiteralPath $env:${PARADIS_MCP_PORT_FILE_ENV_VAR} -Raw), '"port"\\s*:\\s*(\\d+)')`,
		'if (-not $portMatch.Success) { exit 0 }',
		'$port = $portMatch.Groups[1].Value',
		'',
		'# Fire-and-forget; a failed request must never fail the agent hook.',
		'# Body is sent as UTF-8 bytes: Windows PowerShell 5.1 would otherwise encode a',
		'# string body as ISO-8859-1 and corrupt non-ASCII JSON content.',
		'try {',
		`  $hookUri = "http://127.0.0.1:$port/agent-hook?pane=$($env:${PARADIS_PANE_TOKEN_ENV_VAR})&event=$eventName"`,
		`  if ($bodyBytes.Length -gt ${PARADIS_AGENT_HOOK_MAX_BODY_BYTES}) {`,
		'    Invoke-RestMethod -Method Get -Uri $hookUri -TimeoutSec 3 | Out-Null',
		'  } else {',
		`    Invoke-RestMethod -Method Post -Uri $hookUri -Body $bodyBytes -ContentType 'application/json' -TimeoutSec 3 | Out-Null`,
		'  }',
		'} catch { }',
		'exit 0',
		'',
	].join('\r\n');
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
	return typeof value === 'object' && value !== null && !Array.isArray(value);
}

/**
 * 当fork管理のhookコマンドかを判定する。notify.sh のパス (マーカー) を含むもの、
 * および旧「Copy Agent Hooks Setup」スニペット由来のcurl 1行コマンド
 * (ポートファイルenvを参照して /agent-hook を叩くもの) を対象とする。
 * ユーザー自身のhook (Superset の notify.sh 等) はここに一致しないため必ず保持される。
 */
function paradisManagedHookSchema(command: unknown): number | undefined {
	if (typeof command !== 'string') {
		return undefined;
	}
	const normalized = command.replace(/\\/g, '/');
	const match = /\/\.para-code\/hooks\/notify-v(\d+)\.(?:sh|ps1)(?:["'\s]|$)/.exec(normalized);
	if (match) {
		return Number(match[1]);
	}
	if (PARADIS_LEGACY_NOTIFY_HOOK_RELATIVE_PATHS.some(path => normalized.includes(`/${path}`))
		|| (normalized.includes(PARADIS_MCP_PORT_FILE_ENV_VAR) && normalized.includes('/agent-hook?pane='))) {
		return 0;
	}
	return undefined;
}

function isParadisManagedHookCommand(command: unknown): boolean {
	return paradisManagedHookSchema(command) !== undefined;
}

function highestParadisManagedHookSchema(hooks: Readonly<Record<string, unknown>>): number | undefined {
	let highest: number | undefined;
	for (const definitions of Object.values(hooks)) {
		if (!Array.isArray(definitions)) {
			continue;
		}
		for (const definition of definitions) {
			if (!isPlainObject(definition) || !Array.isArray(definition['hooks'])) {
				continue;
			}
			for (const hook of definition['hooks']) {
				const schema = isPlainObject(hook) ? paradisManagedHookSchema(hook['command']) : undefined;
				if (schema !== undefined && (highest === undefined || schema > highest)) {
					highest = schema;
				}
			}
		}
	}
	return highest;
}

/**
 * hook定義配列から当fork管理のhookだけを取り除く (ユーザーhookは構造ごと保持)。
 * 定義の hooks 配列が空になった場合は定義自体を落とす。
 */
function removeManagedHooksFromDefinitions(definitions: readonly unknown[]): unknown[] {
	const result: unknown[] = [];
	for (const definition of definitions) {
		if (!isPlainObject(definition) || !Array.isArray(definition['hooks'])) {
			result.push(definition);
			continue;
		}
		const hooks = definition['hooks'] as readonly unknown[];
		const filtered = hooks.filter(hook => !(isPlainObject(hook) && isParadisManagedHookCommand(hook['command'])));
		if (filtered.length === hooks.length) {
			result.push(definition);
			continue;
		}
		if (filtered.length === 0) {
			continue;
		}
		result.push({ ...definition, hooks: filtered });
	}
	return result;
}

/**
 * 既存の settings.json / hooks.json (生テキスト) に当fork管理のhook定義を冪等マージし、
 * 新しいJSON文字列を返す。パース不能・ルートがオブジェクトでない場合は undefined
 * (呼び出し側は何も書かない)。既存のユーザーhook・その他の設定キーはすべて保持する。
 * 2回適用しても結果が変わらない (先に自hookを全除去してから追記し直すため)。
 */
export function paradisMergeAgentHooksJson(existingRaw: string | undefined, managedEvents: readonly IParadisManagedHookEvent[], hookCommand?: string): string | undefined {
	let parsed: unknown = {};
	if (existingRaw !== undefined && existingRaw.trim().length > 0) {
		try {
			parsed = JSON.parse(existingRaw);
		} catch {
			return undefined;
		}
	}
	if (!isPlainObject(parsed)) {
		return undefined;
	}
	const hooksValue = parsed['hooks'];
	const hooks: Record<string, unknown> = isPlainObject(hooksValue) ? hooksValue : {};
	parsed['hooks'] = hooks;
	const existingSchema = highestParadisManagedHookSchema(hooks);
	if (existingSchema !== undefined && existingSchema > PARADIS_AGENT_HOOK_SCHEMA_VERSION) {
		return existingRaw;
	}

	// 全イベントから当fork管理のhookを一旦取り除く。もう登録しないイベント
	// (旧スニペットの PreToolUse 等) に残った自hookの掃除も兼ねる。
	for (const eventName of Object.keys(hooks)) {
		const current = hooks[eventName];
		if (!Array.isArray(current)) {
			continue;
		}
		const filtered = removeManagedHooksFromDefinitions(current);
		if (filtered.length === 0 && current.length > 0 && !managedEvents.some(e => e.eventName === eventName)) {
			delete hooks[eventName];
		} else {
			hooks[eventName] = filtered;
		}
	}

	// 管理対象イベントへ自hookを追記する (既存ユーザーhookは上で保持済み)。
	for (const event of managedEvents) {
		const definition = paradisManagedHookDefinition(event, hookCommand);
		const current = hooks[event.eventName];
		if (Array.isArray(current)) {
			current.push(definition);
		} else {
			hooks[event.eventName] = [definition];
		}
	}

	return JSON.stringify(parsed, undefined, 2);
}

/** notify.sh (POSIX) / notify.ps1 (Windows) を冪等生成する (内容一致なら実行権の確認のみ)。 */
async function installNotifyScript(logService: ILogService): Promise<void> {
	try {
		const isWindows = process.platform === 'win32';
		const scriptPath = join(homedir(), isWindows ? PARADIS_NOTIFY_HOOK_RELATIVE_PATH_PS1 : PARADIS_NOTIFY_HOOK_RELATIVE_PATH);
		const content = isWindows ? paradisGetNotifyScriptContentPs1() : paradisGetNotifyScriptContent();
		let existing: string | undefined;
		try {
			existing = await fs.readFile(scriptPath, 'utf8');
		} catch {
			existing = undefined;
		}
		if (existing === content) {
			try {
				await fs.chmod(scriptPath, 0o755);
			} catch {
				// 実行権の再付与はベストエフォート
			}
			return;
		}
		await fs.mkdir(dirname(scriptPath), { recursive: true });
		await fs.writeFile(scriptPath, content, { mode: 0o755 });
		// writeFile の mode は新規作成時のみ有効なため、既存ファイル上書き時に備えて明示 chmod する
		await fs.chmod(scriptPath, 0o755);
		logService.info(`[ParadisAgentHooks] Installed notify hook script: ${scriptPath}`);
	} catch (error) {
		logService.warn('[ParadisAgentHooks] Failed to install notify hook script', error);
	}
}

export interface IParadisAgentHooksFileIO {
	readFile(filePath: string): Promise<string | undefined>;
	writeFileIfUnchanged(filePath: string, expected: string | undefined, content: string): boolean;
	mkdir(directory: string): Promise<void>;
}

const defaultAgentHooksFileIO: IParadisAgentHooksFileIO = {
	async readFile(filePath) {
		try {
			return await fs.readFile(filePath, 'utf8');
		} catch {
			return undefined;
		}
	},
	writeFileIfUnchanged(filePath, expected, content) {
		let current: string | undefined;
		try {
			current = readFileSync(filePath, 'utf8');
		} catch {
			current = undefined;
		}
		if (current !== expected) {
			return false;
		}
		// 比較後にイベントループへ制御を返さず直ちに保存し、外部writerとの競合窓を
		// 最小化する。非協調プロセスとの完全なCASは通常ファイルAPIでは不可能だが、
		// 少なくともPara Code自身が非同期処理を挟んで古い内容を書くことはない。
		writeFileSync(filePath, content);
		return true;
	},
	async mkdir(directory) {
		await fs.mkdir(directory, { recursive: true });
	},
};

/**
 * 設定ファイル1つ分の冪等マージ + 書き込み。書き込み直前に再読込し、外部更新が
 * 入っていれば最新内容からマージし直す。上限内に安定しなければユーザーファイルを
 * 優先して書き込みを見送る。失敗しても例外は投げない。
 */
export async function paradisMergeAgentHooksFile(filePath: string, managedEvents: readonly IParadisManagedHookEvent[], logService: ILogService | undefined, hookCommand?: string, io: IParadisAgentHooksFileIO = defaultAgentHooksFileIO): Promise<void> {
	try {
		await io.mkdir(dirname(filePath));
		for (let attempt = 0; attempt < 3; attempt++) {
			const existingRaw = await io.readFile(filePath);
			const merged = paradisMergeAgentHooksJson(existingRaw, managedEvents, hookCommand);
			if (merged === undefined) {
				logService?.warn(`[ParadisAgentHooks] Could not parse ${filePath}; skipping hook merge (user file left untouched)`);
				return;
			}
			// 既存ファイルの末尾改行は維持する (余計な毎回書き込みを防ぐ)
			const content = existingRaw !== undefined && existingRaw.endsWith('\n') ? `${merged}\n` : merged;
			if (content === existingRaw) {
				return; // 既に最新
			}
			// read→write間にユーザーや別ツールが保存していれば、古いスナップショットで
			// 上書きせず、最新内容を起点に再マージする。
			if (!io.writeFileIfUnchanged(filePath, existingRaw, content)) {
				continue;
			}
			logService?.info(`[ParadisAgentHooks] Updated agent hooks in ${filePath}`);
			return;
		}
		logService?.warn(`[ParadisAgentHooks] ${filePath} kept changing during hook merge; skipped update to preserve external changes`);
	} catch (error) {
		logService?.warn(`[ParadisAgentHooks] Failed to update ${filePath}`, error);
	}
}

/**
 * activity追加hookとMessageDisplayはClaude Code 2.1.207でpayloadを一括確認した。
 * 旧版の settings.json は未知のhookキーを拒否し得るため、バージョンを確認できない場合も
 * 安全側に倒して登録しない。判定は起動を妨げない短いベストエフォートとする。
 */
export function paradisSupportsClaudeActivityHooks(versionOutput: string): boolean {
	const match = /(\d+)\.(\d+)\.(\d+)/.exec(versionOutput);
	if (!match) {
		return false;
	}
	const major = Number(match[1]);
	const minor = Number(match[2]);
	const patch = Number(match[3]);
	return major > 2 || (major === 2 && (minor > 1 || (minor === 1 && patch >= 207)));
}

export function paradisSupportsClaudeMessageDisplay(versionOutput: string): boolean {
	const match = /(\d+)\.(\d+)\.(\d+)/.exec(versionOutput);
	if (!match) {
		return false;
	}
	const major = Number(match[1]);
	const minor = Number(match[2]);
	const patch = Number(match[3]);
	return major > 2 || (major === 2 && (minor > 1 || (minor === 1 && patch >= 205)));
}

const PARADIS_CLAUDE_VERSION_TIMEOUT_MS = 15_000;
const PARADIS_CLAUDE_VERSION_MAX_ATTEMPTS = 3;

type ClaudeVersionProbeFailureStage = 'shell-env' | 'not-found' | 'spawn' | 'timeout' | 'exit' | 'unparseable';

type ClaudeVersionProbeResult =
	| { readonly outcome: 'success'; readonly versionOutput: string }
	| { readonly outcome: 'failure'; readonly stage: ClaudeVersionProbeFailureStage; readonly detail?: string };

function claudeVersionProbeErrorDetail(error: Error & { readonly code?: string | number; readonly killed?: boolean; readonly signal?: string }, executable: string, stderr: string): string {
	const parts = [`executable=${executable}`];
	if (error.code !== undefined) {
		parts.push(`code=${error.code}`);
	}
	if (error.signal !== undefined) {
		parts.push(`signal=${error.signal}`);
	}
	const trimmedStderr = stderr.trim().slice(0, 500);
	if (trimmedStderr) {
		parts.push(`stderr=${JSON.stringify(trimmedStderr)}`);
	}
	return parts.join(', ');
}

async function probeClaudeVersion(shellEnvResolver: () => Promise<NodeJS.ProcessEnv>): Promise<ClaudeVersionProbeResult> {
	let env: NodeJS.ProcessEnv;
	try {
		env = await shellEnvResolver();
	} catch (error) {
		return { outcome: 'failure', stage: 'shell-env', detail: error instanceof Error ? error.message : String(error) };
	}
	let executable: string | undefined;
	try {
		executable = await findExecutable('claude', undefined, undefined, env);
	} catch (error) {
		return { outcome: 'failure', stage: 'spawn', detail: `executable resolution failed: ${error instanceof Error ? error.message : String(error)}` };
	}
	if (executable === undefined) {
		return { outcome: 'failure', stage: 'not-found' };
	}
	return new Promise(resolve => {
		execFile(executable, ['--version'], { encoding: 'utf8', timeout: PARADIS_CLAUDE_VERSION_TIMEOUT_MS, windowsHide: true, env }, (error, stdout, stderr) => {
			if (error) {
				const typedError = error as Error & { readonly code?: string | number; readonly killed?: boolean; readonly signal?: string };
				const stage: ClaudeVersionProbeFailureStage = typedError.killed ? 'timeout' : typeof typedError.code === 'number' ? 'exit' : 'spawn';
				resolve({ outcome: 'failure', stage, detail: claudeVersionProbeErrorDetail(typedError, executable, stderr) });
				return;
			}
			if (!/(\d+)\.(\d+)\.(\d+)/.test(stdout)) {
				resolve({ outcome: 'failure', stage: 'unparseable', detail: `executable=${executable}, stdout=${JSON.stringify(stdout.trim().slice(0, 200))}` });
				return;
			}
			resolve({ outcome: 'success', versionOutput: stdout });
		});
	});
}

const PARADIS_AGENT_HOOK_RECONCILE_DELAY_MS = 500;
const PARADIS_AGENT_HOOK_AUDIT_INTERVAL_MS = 60_000;

export interface IParadisAgentHooksReconcilerOptions {
	readonly claudeSettingsPath?: string;
	readonly codexHooksPath?: string;
	readonly claudeVersionOutput?: string;
	readonly installNotifyScript?: boolean;
	readonly watchDirectory?: (directory: string, listener: (fileName: string | null) => void) => IDisposable;
	readonly scheduleReconcile?: (listener: () => void) => IDisposable;
	readonly scheduleAudit?: (listener: () => void) => IDisposable;
	readonly reconcileFiles?: () => Promise<void>;
}

/**
 * Para Code管理hookの存在だけを継続的に整合させる。ファイル変更時も必ず最新JSONを
 * 読み直して既存hookへ追加マージするため、ユーザーや他ツールのhookは保持される。
 * ディレクトリwatchは即時復旧用、定期監査はwatchイベント欠落・watcher停止時の保険。
 */
export class ParadisAgentHooksReconciler extends Disposable {
	private readonly claudeSettingsPath: string;
	private readonly codexHooksPath: string;
	private readonly watchDirectory: (directory: string, listener: (fileName: string | null) => void) => IDisposable;
	private readonly scheduleReconcile: (listener: () => void) => IDisposable;
	private readonly scheduleAudit: (listener: () => void) => IDisposable;
	private reconcileTail: Promise<void> = Promise.resolve();
	private pendingReconcile: IDisposable | undefined;
	private started = false;
	private disposed = false;
	private notifyScriptInstalled = false;
	private capabilityLogged = false;
	private claudeVersion: string | undefined;
	private claudeVersionProbePromise: Promise<string | undefined> | undefined;
	private claudeVersionAttempts = 0;

	constructor(
		private readonly logService: ILogService | undefined,
		private readonly options: IParadisAgentHooksReconcilerOptions = {},
		private readonly shellEnvResolver: () => Promise<NodeJS.ProcessEnv> = () => Promise.resolve({ ...process.env }),
	) {
		super();
		this.claudeSettingsPath = options.claudeSettingsPath ?? join(paradisClaudeConfigDir(), 'settings.json');
		this.codexHooksPath = options.codexHooksPath ?? join(paradisCodexHome(), 'hooks.json');
		this.watchDirectory = options.watchDirectory ?? ((directory, listener) => {
			try {
				const watcher = watch(directory, { persistent: false }, (_eventType, fileName) => listener(fileName?.toString() ?? null));
				watcher.on('error', error => this.logService?.warn(`[ParadisAgentHooks] Hook settings watcher failed for ${directory}; periodic audit remains active`, error));
				return toDisposable(() => watcher.close());
			} catch (error) {
				this.logService?.warn(`[ParadisAgentHooks] Could not watch ${directory}; periodic audit remains active`, error);
				return Disposable.None;
			}
		});
		this.scheduleReconcile = options.scheduleReconcile ?? (listener => {
			const handle = setTimeout(listener, PARADIS_AGENT_HOOK_RECONCILE_DELAY_MS);
			return toDisposable(() => clearTimeout(handle));
		});
		this.scheduleAudit = options.scheduleAudit ?? (listener => {
			const handle = setInterval(listener, PARADIS_AGENT_HOOK_AUDIT_INTERVAL_MS);
			return toDisposable(() => clearInterval(handle));
		});
	}

	async start(): Promise<void> {
		if (this.started || this.disposed) {
			return;
		}
		this.started = true;
		await this.reconcile();
		if (this.disposed) {
			return;
		}
		for (const directory of new Set([dirname(this.claudeSettingsPath), dirname(this.codexHooksPath)])) {
			this._register(this.watchDirectory(directory, fileName => this.onDirectoryChange(fileName)));
		}
		this._register(this.scheduleAudit(() => { void this.reconcile(); }));
	}

	private onDirectoryChange(fileName: string | null): void {
		if (this.disposed || (fileName !== null && fileName !== basename(this.claudeSettingsPath) && fileName !== basename(this.codexHooksPath))) {
			return;
		}
		if (this.pendingReconcile !== undefined) {
			return;
		}
		this.pendingReconcile = this.scheduleReconcile(() => {
			this.pendingReconcile = undefined;
			if (!this.disposed) {
				void this.reconcile(false);
			}
		});
	}

	reconcile(allowVersionProbe: boolean = true): Promise<void> {
		if (this.disposed) {
			return this.reconcileTail;
		}
		const run = this.options.reconcileFiles ?? (() => this.reconcileManagedFiles(allowVersionProbe));
		this.reconcileTail = this.reconcileTail.then(run, run);
		return this.reconcileTail;
	}

	whenIdle(): Promise<void> {
		return this.reconcileTail;
	}

	private async resolveClaudeVersion(allowProbe: boolean): Promise<string | undefined> {
		if (this.options.claudeVersionOutput !== undefined) {
			this.claudeVersion = this.options.claudeVersionOutput;
			return this.claudeVersion;
		}
		if (this.claudeVersion !== undefined || !allowProbe || this.claudeVersionAttempts >= PARADIS_CLAUDE_VERSION_MAX_ATTEMPTS) {
			return this.claudeVersion;
		}
		if (this.claudeVersionProbePromise === undefined) {
			const attempt = ++this.claudeVersionAttempts;
			this.claudeVersionProbePromise = probeClaudeVersion(this.shellEnvResolver).then(result => {
				if (result.outcome === 'success') {
					this.claudeVersion = result.versionOutput;
					return result.versionOutput;
				}
				const detail = result.detail ? ` (${result.detail})` : '';
				const exhausted = attempt >= PARADIS_CLAUDE_VERSION_MAX_ATTEMPTS ? '; retry limit reached for this process' : '';
				this.logService?.warn(`[ParadisAgentHooks] Claude version probe failed at ${result.stage}, attempt ${attempt}/${PARADIS_CLAUDE_VERSION_MAX_ATTEMPTS}${detail}${exhausted}`);
				return undefined;
			}).finally(() => {
				this.claudeVersionProbePromise = undefined;
			});
		}
		return this.claudeVersionProbePromise;
	}

	private async reconcileManagedFiles(allowVersionProbe: boolean): Promise<void> {
		if (this.options.installNotifyScript !== false && !this.notifyScriptInstalled && this.logService !== undefined) {
			await installNotifyScript(this.logService);
			this.notifyScriptInstalled = true;
		}
		const hookCommand = process.platform === 'win32' ? paradisManagedAgentHookCommandWindows(homedir()) : undefined;
		const claudeVersion = await this.resolveClaudeVersion(allowVersionProbe);
		const claudeEvents = [
			...PARADIS_CLAUDE_HOOK_EVENTS,
			...(claudeVersion !== undefined && paradisSupportsClaudeActivityHooks(claudeVersion) ? PARADIS_CLAUDE_ACTIVITY_HOOK_EVENTS : []),
			...(claudeVersion !== undefined && paradisSupportsClaudeMessageDisplay(claudeVersion) ? [PARADIS_CLAUDE_MESSAGE_DISPLAY_HOOK_EVENT] : []),
		];
		if (claudeVersion === undefined || !paradisSupportsClaudeActivityHooks(claudeVersion)) {
			this.logService?.trace('[ParadisAgentHooks] Claude activity hook support not confirmed; leaving version-dependent hooks disabled');
		}
		if (!this.capabilityLogged && (claudeVersion !== undefined || this.claudeVersionAttempts >= PARADIS_CLAUDE_VERSION_MAX_ATTEMPTS)) {
			this.capabilityLogged = true;
			this.logService?.info(`[ParadisAgentHooks] Claude version ${claudeVersion?.trim() ?? 'unknown'}; managed events: ${claudeEvents.map(event => event.eventName).join(', ')}`);
		}
		await paradisMergeAgentHooksFile(this.claudeSettingsPath, claudeEvents, this.logService, hookCommand);
		await paradisMergeAgentHooksFile(this.codexHooksPath, PARADIS_CODEX_HOOK_EVENTS, this.logService, hookCommand);
	}

	override dispose(): void {
		this.disposed = true;
		this.pendingReconcile?.dispose();
		this.pendingReconcile = undefined;
		super.dispose();
	}
}

/**
 * hook自動設置のエントリポイント。ParadisAgentBrowserService 起動時に fire-and-forget で
 * 呼ばれる。各ステップは内部でエラーを握りつぶすため、この関数が起動を妨げることはない。
 * Windows は notify.ps1 を設置し、hookコマンドは powershell 直接起動形式にする
 * (Claude Code のhookは Git Bash または PowerShell、Codex のhookは cmd /C で実行される。
 * 3シェルすべてで同じ意味になる形式は「powershell.exe を絶対パス引数で起動」のみ)。
 */
export async function paradisSetupAgentHooks(logService: ILogService, shellEnvResolver: () => Promise<NodeJS.ProcessEnv> = () => Promise.resolve({ ...process.env })): Promise<void> {
	await installNotifyScript(logService);
	// Windows のhookコマンドは各シェルの変数展開仕様の違いを避けるため絶対パス埋め込み。
	// POSIX は従来どおり $HOME 参照の固定文字列 (undefined → paradisManagedHookDefinition の既定)。
	const hookCommand = process.platform === 'win32' ? paradisManagedAgentHookCommandWindows(homedir()) : undefined;
	// $CLAUDE_CONFIG_DIR / $CODEX_HOME でhomeを移動しているユーザーにも設置が届くよう、
	// 設置先はハードコードではなく解決関数を通す (未設定なら従来どおり ~/.claude / ~/.codex)。
	const claudeVersionProbe = await probeClaudeVersion(shellEnvResolver);
	const claudeVersion = claudeVersionProbe.outcome === 'success' ? claudeVersionProbe.versionOutput : undefined;
	if (claudeVersionProbe.outcome === 'failure') {
		const detail = claudeVersionProbe.detail ? ` (${claudeVersionProbe.detail})` : '';
		logService.warn(`[ParadisAgentHooks] Claude version probe failed at ${claudeVersionProbe.stage}, attempt 1/1${detail}`);
	}
	const claudeEvents = [
		...PARADIS_CLAUDE_HOOK_EVENTS,
		...(claudeVersion !== undefined && paradisSupportsClaudeActivityHooks(claudeVersion) ? PARADIS_CLAUDE_ACTIVITY_HOOK_EVENTS : []),
		...(claudeVersion !== undefined && paradisSupportsClaudeMessageDisplay(claudeVersion) ? [PARADIS_CLAUDE_MESSAGE_DISPLAY_HOOK_EVENT] : []),
	];
	if (claudeVersion === undefined || !paradisSupportsClaudeActivityHooks(claudeVersion)) {
		logService.trace('[ParadisAgentHooks] Claude activity hook support not confirmed; leaving version-dependent hooks disabled');
	}
	await paradisMergeAgentHooksFile(join(paradisClaudeConfigDir(), 'settings.json'), claudeEvents, logService, hookCommand);
	await paradisMergeAgentHooksFile(join(paradisCodexHome(), 'hooks.json'), PARADIS_CODEX_HOOK_EVENTS, logService, hookCommand);
}
