/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/
// allow-any-unicode-comment-file (Para Code: this file contains Japanese PARA-PATCH/PARA-CODE comments)

// PARA-CODE: fork-owned file (Para Code) — not present in upstream microsoft/vscode. See CLAUDE.md.

// エージェントCLI (Claude Code / Codex) の通知hookを自動設置する (Superset の setupAgentHooks 移植)。
// shared process の ParadisAgentBrowserService 起動時に冪等実行される。
// 1. ~/.para-code/hooks/notify.sh を生成 (実行権付き)。スクリプトは Para Code のターミナル外
//    (ペイントークンenvなし) では即 exit 0 する無害設計。
// 2. ~/.claude/settings.json へhook定義を冪等マージ (既存のユーザーhookは保持)。
// 3. ~/.codex/hooks.json へhook定義を冪等マージ (同上)。
// 既存ファイルのJSONパースに失敗した場合は何も書かない (ユーザーファイルを壊すくらいなら諦める)。

import { execFile } from 'child_process';
import { promises as fs } from 'fs';
import { homedir } from 'os';
import { dirname, join } from '../../../../base/common/path.js';
import { ILogService } from '../../../../platform/log/common/log.js';
import { PARADIS_MCP_PORT_FILE_ENV_VAR, PARADIS_PANE_TOKEN_ENV_VAR } from '../common/paradisAgentBrowser.js';
import { IParadisManagedHookEvent, PARADIS_AGENT_HOOK_SCHEMA_VERSION, PARADIS_CLAUDE_ACTIVITY_HOOK_EVENTS, PARADIS_CLAUDE_HOOK_EVENTS, PARADIS_CLAUDE_MESSAGE_DISPLAY_HOOK_EVENT, PARADIS_CODEX_HOOK_EVENTS, PARADIS_LEGACY_NOTIFY_HOOK_RELATIVE_PATHS, PARADIS_NOTIFY_HOOK_RELATIVE_PATH, PARADIS_NOTIFY_HOOK_RELATIVE_PATH_PS1, paradisManagedAgentHookCommandWindows, paradisManagedHookDefinition } from '../common/paradisAgentHooks.js';
import { paradisClaudeConfigDir, paradisCodexHome } from './paradisAgentHome.js';

/**
 * notify.sh の内容を生成する (全行ASCII)。jq には依存せず grep/sed のみでパースする。
 * - Para Code のターミナル外 (env なし) では即 exit 0
 * - イベント名は stdin JSON の `hook_event_name` (Claude Code) / `type` (Codex notify) から取得。
 *   パース失敗時は黙って捨てる (誤った完了通知より安全)
 * - curl の失敗が hook 全体を fail させないよう `|| true` で必ず正常終了する
 */
export function paradisGetNotifyScriptContent(): string {
	return [
		'#!/bin/sh',
		'# Para Code agent notification hook v2',
		'# Auto-generated by Para Code (paradisAgentHooksSetup.ts); regenerated on startup.',
		'# Forwards Claude Code / Codex hook events to the Para Code shared process',
		'# (GET /agent-hook). Outside Para Code terminals this script exits immediately.',
		'',
		`[ -n "\${${PARADIS_PANE_TOKEN_ENV_VAR}:-}" ] || exit 0`,
		`[ -n "\${${PARADIS_MCP_PORT_FILE_ENV_VAR}:-}" ] || exit 0`,
		`[ -f "$${PARADIS_MCP_PORT_FILE_ENV_VAR}" ] || exit 0`,
		'',
		'# Codex notify passes JSON as argv[1]; Claude Code pipes JSON via stdin.',
		'if [ -n "${1:-}" ]; then',
		'  INPUT="$1"',
		'else',
		'  INPUT=$(cat 2>/dev/null || true)',
		'fi',
		'',
		'# Claude Code uses "hook_event_name"; Codex uses "type". No jq dependency.',
		`EVENT=$(printf '%s' "$INPUT" | grep -oE '"hook_event_name"[[:space:]]*:[[:space:]]*"[^"]*"' | head -n 1 | sed -E 's/.*"([^"]*)"$/\\1/')`,
		'if [ -z "$EVENT" ]; then',
		`  EVENT=$(printf '%s' "$INPUT" | grep -oE '"type"[[:space:]]*:[[:space:]]*"[^"]*"' | head -n 1 | sed -E 's/.*"([^"]*)"$/\\1/')`,
		'fi',
		'# Never guess on parse failure: dropping is safer than a false notification.',
		'[ -n "$EVENT" ] || exit 0',
		'# Keep the query value URL-safe (event names are plain identifiers).',
		`EVENT=$(printf '%s' "$EVENT" | tr -cd 'A-Za-z0-9._-')`,
		'[ -n "$EVENT" ] || exit 0',
		'',
		`PORT=$(sed -nE 's/.*"port"[[:space:]]*:[[:space:]]*([0-9]+).*/\\1/p' "$${PARADIS_MCP_PORT_FILE_ENV_VAR}" 2>/dev/null | head -n 1)`,
		'[ -n "$PORT" ] || exit 0',
		'',
		'# Fire-and-forget; a failed curl must never fail the agent hook.',
		'# v2: POST the raw hook JSON so the shared process can read session_id /',
		'# transcript_path (used by the mobile agent-chat mirror). The event query',
		'# parameter is kept for the status logic and for backward compatibility.',
		`printf '%s' "$INPUT" | curl -s -m 3 -X POST -H "Content-Type: application/json" --data-binary @- "http://127.0.0.1:$PORT/agent-hook?pane=$${PARADIS_PANE_TOKEN_ENV_VAR}&event=$EVENT" >/dev/null 2>&1 || true`,
		'exit 0',
		'',
	].join('\n');
}

/**
 * notify.ps1 の内容を生成する (全行ASCII、Windows用)。役割・防御方針は notify.sh と同一:
 * - Para Code のターミナル外 (env なし) では即 exit 0
 * - イベント名は stdin JSON (Claude Code / Codex 新hooks) の `hook_event_name`、
 *   または argv[1] (Codex legacy notify) の `type` から取得。パース失敗は黙って捨てる
 * - POST の失敗が hook 全体を fail させないよう try/catch で必ず正常終了する
 */
export function paradisGetNotifyScriptContentPs1(): string {
	return [
		'# Para Code agent notification hook v2 (PowerShell)',
		'# Auto-generated by Para Code (paradisAgentHooksSetup.ts); regenerated on startup.',
		'# Forwards Claude Code / Codex hook events to the Para Code shared process',
		'# (POST /agent-hook). Outside Para Code terminals this script exits immediately.',
		'param([string]$HookArg)',
		'$ErrorActionPreference = \'SilentlyContinue\'',
		`if (-not $env:${PARADIS_PANE_TOKEN_ENV_VAR}) { exit 0 }`,
		`if (-not $env:${PARADIS_MCP_PORT_FILE_ENV_VAR}) { exit 0 }`,
		`if (-not (Test-Path -LiteralPath $env:${PARADIS_MCP_PORT_FILE_ENV_VAR})) { exit 0 }`,
		'',
		'# Codex legacy notify passes JSON as argv[1]; hooks pipe JSON via stdin.',
		'if ($HookArg) { $inputJson = $HookArg } else { $inputJson = [Console]::In.ReadToEnd() }',
		'if (-not $inputJson) { exit 0 }',
		'',
		'# Claude Code and Codex hooks use "hook_event_name"; Codex legacy notify uses "type".',
		'$eventMatch = [regex]::Match($inputJson, \'"hook_event_name"\\s*:\\s*"([^"]*)"\')',
		'if (-not $eventMatch.Success) { $eventMatch = [regex]::Match($inputJson, \'"type"\\s*:\\s*"([^"]*)"\') }',
		'# Never guess on parse failure: dropping is safer than a false notification.',
		'if (-not $eventMatch.Success) { exit 0 }',
		'# Keep the query value URL-safe (event names are plain identifiers).',
		'$eventName = $eventMatch.Groups[1].Value -replace \'[^A-Za-z0-9._-]\', \'\'',
		'if (-not $eventName) { exit 0 }',
		'',
		`$portMatch = [regex]::Match((Get-Content -LiteralPath $env:${PARADIS_MCP_PORT_FILE_ENV_VAR} -Raw), '"port"\\s*:\\s*(\\d+)')`,
		'if (-not $portMatch.Success) { exit 0 }',
		'$port = $portMatch.Groups[1].Value',
		'',
		'# Fire-and-forget; a failed request must never fail the agent hook.',
		'# Body is sent as UTF-8 bytes: Windows PowerShell 5.1 would otherwise encode a',
		'# string body as ISO-8859-1 and corrupt non-ASCII JSON content.',
		'try {',
		'  $bodyBytes = [System.Text.Encoding]::UTF8.GetBytes($inputJson)',
		`  Invoke-RestMethod -Method Post -Uri "http://127.0.0.1:$port/agent-hook?pane=$($env:${PARADIS_PANE_TOKEN_ENV_VAR})&event=$eventName" -Body $bodyBytes -ContentType 'application/json' -TimeoutSec 3 | Out-Null`,
		'} catch { }',
		'exit 0',
		'',
	].join('\r\n');
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
	return typeof value === 'object' && value !== null && !Array.isArray(value);
}

/**
 * 当fork管理のhookコマンドかを判定する。notify.sh のパス (マーカー) を含むもの、
 * および旧「Copy Agent Hooks Setup」スニペット由来のcurl 1行コマンド
 * (ポートファイルenvを参照して /agent-hook を叩くもの) を対象とする。
 * ユーザー自身のhook (Superset の notify.sh 等) はここに一致しないため必ず保持される。
 */
function paradisManagedHookSchema(command: unknown): number | undefined {
	if (typeof command !== 'string') {
		return undefined;
	}
	const normalized = command.replace(/\\/g, '/');
	const match = /\/\.para-code\/hooks\/notify-v(\d+)\.(?:sh|ps1)(?:["'\s]|$)/.exec(normalized);
	if (match) {
		return Number(match[1]);
	}
	if (PARADIS_LEGACY_NOTIFY_HOOK_RELATIVE_PATHS.some(path => normalized.includes(`/${path}`))
		|| (normalized.includes(PARADIS_MCP_PORT_FILE_ENV_VAR) && normalized.includes('/agent-hook?pane='))) {
		return 0;
	}
	return undefined;
}

function isParadisManagedHookCommand(command: unknown): boolean {
	return paradisManagedHookSchema(command) !== undefined;
}

function highestParadisManagedHookSchema(hooks: Readonly<Record<string, unknown>>): number | undefined {
	let highest: number | undefined;
	for (const definitions of Object.values(hooks)) {
		if (!Array.isArray(definitions)) {
			continue;
		}
		for (const definition of definitions) {
			if (!isPlainObject(definition) || !Array.isArray(definition['hooks'])) {
				continue;
			}
			for (const hook of definition['hooks']) {
				const schema = isPlainObject(hook) ? paradisManagedHookSchema(hook['command']) : undefined;
				if (schema !== undefined && (highest === undefined || schema > highest)) {
					highest = schema;
				}
			}
		}
	}
	return highest;
}

/**
 * hook定義配列から当fork管理のhookだけを取り除く (ユーザーhookは構造ごと保持)。
 * 定義の hooks 配列が空になった場合は定義自体を落とす。
 */
function removeManagedHooksFromDefinitions(definitions: readonly unknown[]): unknown[] {
	const result: unknown[] = [];
	for (const definition of definitions) {
		if (!isPlainObject(definition) || !Array.isArray(definition['hooks'])) {
			result.push(definition);
			continue;
		}
		const hooks = definition['hooks'] as readonly unknown[];
		const filtered = hooks.filter(hook => !(isPlainObject(hook) && isParadisManagedHookCommand(hook['command'])));
		if (filtered.length === hooks.length) {
			result.push(definition);
			continue;
		}
		if (filtered.length === 0) {
			continue;
		}
		result.push({ ...definition, hooks: filtered });
	}
	return result;
}

/**
 * 既存の settings.json / hooks.json (生テキスト) に当fork管理のhook定義を冪等マージし、
 * 新しいJSON文字列を返す。パース不能・ルートがオブジェクトでない場合は undefined
 * (呼び出し側は何も書かない)。既存のユーザーhook・その他の設定キーはすべて保持する。
 * 2回適用しても結果が変わらない (先に自hookを全除去してから追記し直すため)。
 */
export function paradisMergeAgentHooksJson(existingRaw: string | undefined, managedEvents: readonly IParadisManagedHookEvent[], hookCommand?: string): string | undefined {
	let parsed: unknown = {};
	if (existingRaw !== undefined && existingRaw.trim().length > 0) {
		try {
			parsed = JSON.parse(existingRaw);
		} catch {
			return undefined;
		}
	}
	if (!isPlainObject(parsed)) {
		return undefined;
	}
	const hooksValue = parsed['hooks'];
	const hooks: Record<string, unknown> = isPlainObject(hooksValue) ? hooksValue : {};
	parsed['hooks'] = hooks;
	const existingSchema = highestParadisManagedHookSchema(hooks);
	if (existingSchema !== undefined && existingSchema > PARADIS_AGENT_HOOK_SCHEMA_VERSION) {
		return existingRaw;
	}

	// 全イベントから当fork管理のhookを一旦取り除く。もう登録しないイベント
	// (旧スニペットの PreToolUse 等) に残った自hookの掃除も兼ねる。
	for (const eventName of Object.keys(hooks)) {
		const current = hooks[eventName];
		if (!Array.isArray(current)) {
			continue;
		}
		const filtered = removeManagedHooksFromDefinitions(current);
		if (filtered.length === 0 && current.length > 0 && !managedEvents.some(e => e.eventName === eventName)) {
			delete hooks[eventName];
		} else {
			hooks[eventName] = filtered;
		}
	}

	// 管理対象イベントへ自hookを追記する (既存ユーザーhookは上で保持済み)。
	for (const event of managedEvents) {
		const definition = paradisManagedHookDefinition(event, hookCommand);
		const current = hooks[event.eventName];
		if (Array.isArray(current)) {
			current.push(definition);
		} else {
			hooks[event.eventName] = [definition];
		}
	}

	return JSON.stringify(parsed, undefined, 2);
}

/** notify.sh (POSIX) / notify.ps1 (Windows) を冪等生成する (内容一致なら実行権の確認のみ)。 */
async function installNotifyScript(logService: ILogService): Promise<void> {
	try {
		const isWindows = process.platform === 'win32';
		const scriptPath = join(homedir(), isWindows ? PARADIS_NOTIFY_HOOK_RELATIVE_PATH_PS1 : PARADIS_NOTIFY_HOOK_RELATIVE_PATH);
		const content = isWindows ? paradisGetNotifyScriptContentPs1() : paradisGetNotifyScriptContent();
		let existing: string | undefined;
		try {
			existing = await fs.readFile(scriptPath, 'utf8');
		} catch {
			existing = undefined;
		}
		if (existing === content) {
			try {
				await fs.chmod(scriptPath, 0o755);
			} catch {
				// 実行権の再付与はベストエフォート
			}
			return;
		}
		await fs.mkdir(dirname(scriptPath), { recursive: true });
		await fs.writeFile(scriptPath, content, { mode: 0o755 });
		// writeFile の mode は新規作成時のみ有効なため、既存ファイル上書き時に備えて明示 chmod する
		await fs.chmod(scriptPath, 0o755);
		logService.info(`[ParadisAgentHooks] Installed notify hook script: ${scriptPath}`);
	} catch (error) {
		logService.warn('[ParadisAgentHooks] Failed to install notify hook script', error);
	}
}

/** 設定ファイル1つ分の冪等マージ + 書き込み。失敗しても例外は投げない。 */
async function mergeHooksFile(filePath: string, managedEvents: readonly IParadisManagedHookEvent[], logService: ILogService, hookCommand?: string): Promise<void> {
	try {
		let existingRaw: string | undefined;
		try {
			existingRaw = await fs.readFile(filePath, 'utf8');
		} catch {
			existingRaw = undefined; // ファイルなし → 新規作成
		}
		const merged = paradisMergeAgentHooksJson(existingRaw, managedEvents, hookCommand);
		if (merged === undefined) {
			logService.warn(`[ParadisAgentHooks] Could not parse ${filePath}; skipping hook merge (user file left untouched)`);
			return;
		}
		// 既存ファイルの末尾改行は維持する (余計な毎回書き込みを防ぐ)
		const content = existingRaw !== undefined && existingRaw.endsWith('\n') ? `${merged}\n` : merged;
		if (content === existingRaw) {
			return; // 既に最新
		}
		await fs.mkdir(dirname(filePath), { recursive: true });
		await fs.writeFile(filePath, content);
		logService.info(`[ParadisAgentHooks] Updated agent hooks in ${filePath}`);
	} catch (error) {
		logService.warn(`[ParadisAgentHooks] Failed to update ${filePath}`, error);
	}
}

/**
 * activity追加hookとMessageDisplayはClaude Code 2.1.207でpayloadを一括確認した。
 * 旧版の settings.json は未知のhookキーを拒否し得るため、バージョンを確認できない場合も
 * 安全側に倒して登録しない。判定は起動を妨げない短いベストエフォートとする。
 */
export function paradisSupportsClaudeActivityHooks(versionOutput: string): boolean {
	const match = /(\d+)\.(\d+)\.(\d+)/.exec(versionOutput);
	if (!match) {
		return false;
	}
	const major = Number(match[1]);
	const minor = Number(match[2]);
	const patch = Number(match[3]);
	return major > 2 || (major === 2 && (minor > 1 || (minor === 1 && patch >= 207)));
}

export function paradisSupportsClaudeMessageDisplay(versionOutput: string): boolean {
	const match = /(\d+)\.(\d+)\.(\d+)/.exec(versionOutput);
	if (!match) {
		return false;
	}
	const major = Number(match[1]);
	const minor = Number(match[2]);
	const patch = Number(match[3]);
	return major > 2 || (major === 2 && (minor > 1 || (minor === 1 && patch >= 205)));
}

async function claudeVersionOutput(shellEnvResolver: () => Promise<NodeJS.ProcessEnv>): Promise<string | undefined> {
	const env = await shellEnvResolver();
	return new Promise(resolve => {
		execFile('claude', ['--version'], { encoding: 'utf8', timeout: 2000, windowsHide: true, env }, (error, stdout) => {
			if (error) {
				resolve(undefined);
				return;
			}
			resolve(stdout);
		});
	});
}

/**
 * hook自動設置のエントリポイント。ParadisAgentBrowserService 起動時に fire-and-forget で
 * 呼ばれる。各ステップは内部でエラーを握りつぶすため、この関数が起動を妨げることはない。
 * Windows は notify.ps1 を設置し、hookコマンドは powershell 直接起動形式にする
 * (Claude Code のhookは Git Bash または PowerShell、Codex のhookは cmd /C で実行される。
 * 3シェルすべてで同じ意味になる形式は「powershell.exe を絶対パス引数で起動」のみ)。
 */
export async function paradisSetupAgentHooks(logService: ILogService, shellEnvResolver: () => Promise<NodeJS.ProcessEnv> = () => Promise.resolve({ ...process.env })): Promise<void> {
	await installNotifyScript(logService);
	// Windows のhookコマンドは各シェルの変数展開仕様の違いを避けるため絶対パス埋め込み。
	// POSIX は従来どおり $HOME 参照の固定文字列 (undefined → paradisManagedHookDefinition の既定)。
	const hookCommand = process.platform === 'win32' ? paradisManagedAgentHookCommandWindows(homedir()) : undefined;
	// $CLAUDE_CONFIG_DIR / $CODEX_HOME でhomeを移動しているユーザーにも設置が届くよう、
	// 設置先はハードコードではなく解決関数を通す (未設定なら従来どおり ~/.claude / ~/.codex)。
	const claudeVersion = await claudeVersionOutput(shellEnvResolver);
	const claudeEvents = [
		...PARADIS_CLAUDE_HOOK_EVENTS,
		...(claudeVersion !== undefined && paradisSupportsClaudeActivityHooks(claudeVersion) ? PARADIS_CLAUDE_ACTIVITY_HOOK_EVENTS : []),
		...(claudeVersion !== undefined && paradisSupportsClaudeMessageDisplay(claudeVersion) ? [PARADIS_CLAUDE_MESSAGE_DISPLAY_HOOK_EVENT] : []),
	];
	if (claudeVersion === undefined || !paradisSupportsClaudeActivityHooks(claudeVersion)) {
		logService.trace('[ParadisAgentHooks] Claude activity hook support not confirmed; leaving version-dependent hooks disabled');
	}
	await mergeHooksFile(join(paradisClaudeConfigDir(), 'settings.json'), claudeEvents, logService, hookCommand);
	await mergeHooksFile(join(paradisCodexHome(), 'hooks.json'), PARADIS_CODEX_HOOK_EVENTS, logService, hookCommand);
}
