/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/
// PARA-CODE: fork-owned file (Para Code) — not present in upstream microsoft/vscode. See CLAUDE.md.

import { importAMDNodeModule } from '../../../../../amdX.js';

export type ParadisOfficeFixturePart = readonly [name: string, content: string | Uint8Array, contentType?: string];

export interface IParadisOfficeFixtureRelationship {
	readonly source?: string;
	readonly id: string;
	readonly type: string;
	readonly target: string;
	readonly targetMode?: 'External';
}

export interface IParadisOfficeFixtureOptions {
	readonly parts: readonly ParadisOfficeFixturePart[];
	readonly relationships?: readonly IParadisOfficeFixtureRelationship[];
}

const FIXED_TIMESTAMP = new Date(1980, 0, 1, 0, 0, 0);

/** テスト用の再現可能な OPC ZIP を作る。 */
export async function buildOpcFixture(options: IParadisOfficeFixtureOptions): Promise<Uint8Array> {
	const parts = new Map<string, { readonly content: string | Uint8Array; readonly contentType: string }>();
	for (const [name, content, contentType] of options.parts) {
		const canonicalName = canonicalPartName(name);
		if (canonicalName === '/[Content_Types].xml') {
			throw new Error('[Content_Types].xml is generated by buildOpcFixture');
		}
		if (parts.has(canonicalName)) {
			throw new Error(`Duplicate OPC part: ${canonicalName}`);
		}
		parts.set(canonicalName, { content, contentType: contentType ?? defaultContentType(canonicalName) });
	}

	for (const [relationshipPart, relationships] of groupRelationships(options.relationships ?? [])) {
		if (parts.has(relationshipPart)) {
			throw new Error(`Relationship part conflicts with fixture part: ${relationshipPart}`);
		}
		parts.set(relationshipPart, {
			content: buildRelationshipsXml(relationships),
			contentType: 'application/vnd.openxmlformats-package.relationships+xml',
		});
	}

	parts.set('/[Content_Types].xml', {
		content: buildContentTypesXml(parts),
		contentType: 'application/xml',
	});

	const JSZip = await importAMDNodeModule<typeof import('jszip')>('jszip', 'dist/jszip.min.js');
	const zip = new JSZip();
	for (const [name, part] of [...parts.entries()].sort(([left], [right]) => compareCodeUnits(left, right))) {
		zip.file(name.slice(1), part.content, { createFolders: false, date: FIXED_TIMESTAMP });
	}

	return zip.generateAsync({ comment: '', compression: 'STORE', platform: 'DOS', type: 'uint8array' });
}

function canonicalPartName(name: string): string {
	if (!name.startsWith('/')) {
		throw new Error(`OPC part names must begin with '/': ${name}`);
	}
	const segments = name.slice(1).split('/');
	if (!segments.length || segments.some(segment => !segment || segment === '.' || segment === '..')) {
		throw new Error(`Invalid OPC part name: ${name}`);
	}
	return `/${segments.join('/')}`;
}

function defaultContentType(name: string): string {
	return name.endsWith('.xml') ? 'application/xml' : 'application/octet-stream';
}

function groupRelationships(relationships: readonly IParadisOfficeFixtureRelationship[]): Map<string, readonly IParadisOfficeFixtureRelationship[]> {
	const groups = new Map<string, IParadisOfficeFixtureRelationship[]>();
	for (const relationship of relationships) {
		const relationshipPart = relationshipPartName(relationship.source);
		const group = groups.get(relationshipPart) ?? [];
		group.push(relationship);
		groups.set(relationshipPart, group);
	}
	return new Map([...groups.entries()]
		.sort(([left], [right]) => compareCodeUnits(left, right))
		.map(([name, group]) => [name, group.sort(compareRelationships)]));
}

function relationshipPartName(source: string | undefined): string {
	if (!source || source === '/') {
		return '/_rels/.rels';
	}
	const canonicalSource = canonicalPartName(source);
	const slashIndex = canonicalSource.lastIndexOf('/');
	return `${canonicalSource.slice(0, slashIndex)}/_rels/${canonicalSource.slice(slashIndex + 1)}.rels`;
}

function compareRelationships(left: IParadisOfficeFixtureRelationship, right: IParadisOfficeFixtureRelationship): number {
	return compareCodeUnits(left.id, right.id)
		|| compareCodeUnits(left.type, right.type)
		|| compareCodeUnits(left.target, right.target)
		|| compareCodeUnits(left.targetMode ?? '', right.targetMode ?? '');
}

function compareCodeUnits(left: string, right: string): number {
	const length = Math.min(left.length, right.length);
	for (let index = 0; index < length; index++) {
		const difference = left.charCodeAt(index) - right.charCodeAt(index);
		if (difference !== 0) {
			return difference;
		}
	}
	return left.length - right.length;
}

function buildContentTypesXml(parts: ReadonlyMap<string, { readonly contentType: string }>): string {
	const overrides = [...parts.entries()]
		.filter(([name]) => name !== '/[Content_Types].xml' && !name.endsWith('.rels'))
		.sort(([left], [right]) => compareCodeUnits(left, right))
		.map(([name, part]) => `<Override PartName="${xmlEscape(name)}" ContentType="${xmlEscape(part.contentType)}"/>`)
		.join('');
	return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>${overrides}</Types>`;
}

function buildRelationshipsXml(relationships: readonly IParadisOfficeFixtureRelationship[]): string {
	const entries = relationships
		.map(relationship => `<Relationship Id="${xmlEscape(relationship.id)}" Type="${xmlEscape(relationship.type)}" Target="${xmlEscape(relationship.target)}"${relationship.targetMode ? ` TargetMode="${relationship.targetMode}"` : ''}/>`)
		.join('');
	return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${entries}</Relationships>`;
}

function xmlEscape(value: string): string {
	return value.replace(/[&<>"]/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[character]!);
}
